# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://sinomiko.github.io
date_format: "ordinal"
title: sinomiko
subtitle: "Make the change"
description: "Miko's Blog"
keywords: miko, xiaoming, sinomiko
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/sinomiko/sinomiko.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Miko Song
organization: Ericsson, Inc.
organization_url: https://www.ericsson.com
location: Shanghai, China
email: mikosong2013@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: sinomiko
douban_username: 
facebook_username: 
weibo_username: 
zhihu_username: 
twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 
disqus_username: 
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns, Matlab]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Linux Kernel,Win32 SDK, DuiLib, WTL, COM, WinDbg]
